config/routes.rb
Rails.application.routes.draw do
 # 管理者用
  devise_for :admin, skip: [:registrations, :password], controllers: {
  sessions: "admin/sessions"
  }
# 顧客用
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

# 管理者側のルーティング
  namespace :admin do
    root to: 'home#top'
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update, :index] do
      collection do
        get 'customer_orders'
      end
    end
    resources :order_details, only: [:update]
    end

# 顧客側のルーティング
  scope module: :public do
    root to: 'homes#top'
    get 'search' => 'searches#search'
    get 'admin/search' => "searches#admin_search"#顧客側検索
    get 'about' => 'homes#about'
    get 'customers/mypage' => 'customers#show'
    get 'customers/infomation/edit' => 'customers#edit'
    patch 'customers/infomation' => 'customers#update'
    get 'customers/confirm' => 'customers#confirm'
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      #collection doは７つのアクション以外の独自のアクションをリソースに追加するものです
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
    resources :addresses, except: [:new, :show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :item_image
  has_many :order_details

  validates :name, presence: true
  validates :introduction, presence: true
  validates :without_tax, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :is_active, inclusion: { in: [true, false] }
  
  def get_item_image(width, height)
    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      item_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpg')
    end
    item_image.variant(resize_to_limit: [width, height]).processed
  end
  
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre
  
  def  add_tax_price #単価(税込)
    (self.without_tax * 1.1).round
  end
  
  def self.looks(word)
    @item = Item.where("name LIKE?", "%#{word}%")#入力したwordが商品の名前に引っかかっているか
  end
  
  def self.search_for(word)
    Item.where('name LIKE ?', '%' + word + '%')
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.all
    @item = Item.all
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @genres = Genre.all
    if @item.save
      flash[:notice] = "商品情報を登録しました"
      redirect_to admin_item_path(@item)
    else
      render "new"
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @genres = Genre.all
    if @item.update(item_params)
      flash[:notice] = "商品情報を変更しました"
      redirect_to admin_item_path(@item)
    else
      render "edit"
    end
  end

  private

  def item_params
    params.require(:item).permit(:item_image, :name, :introduction, :genre_id, :without_tax, :is_active)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/_error.html.erb
<% if @item.errors.any? %>
  <ul class="alert alert-danger" role="alert">
    <h6 class="alert-heading">
      <%= @item.errors.count %>件のエラーが発生しました
    </h6>
   <% @item.errors.full_messages.each do |message| %>
    <li><%= message %></li>
   <% end %>
  </ul>
<% end %>

app/views/admin/items/_flash.html.erb
<% if flash[:notice].present? %>
   <div class="alert alert-success">
     <%= flash[:notice] %>
   </div>
<% end %>

app/views/admin/items/_form.html.erb
<div class="form-group">
  <%= f.label :item_image, "商品画像", style: "margin-right:60px;" %>
  <%= f.file_field :item_image, accept: "image/*" %>
</div>
<div class="form-group">
  <%= f.label :item_name, "商品名", style: "margin-right:75px;" %>
  <%= f.text_field :name, placeholder:"商品名", size: "31x1" %>
</div>
<div class="form-group">
  <%= f.label :item_introduction, "商品説明", style: "margin-right:60px;", class: "align-top" %>
  <%= f.text_area :introduction, placeholder:"ここに説明文を記述します", size: "30x5" %>
</div>
<div class="form-group">
  <%= f.label :genre, "ジャンル", style:"margin-right:60px;" %>
  <%= f.collection_select :genre_id, genres, :id, :name, include_blank: "--選択してください--", size: "30x1" %>
</div>
<div class="form-group">
  <%= f.label :without_tax, "税抜価格", style:"margin-right:60px;" %>
  <%= f.text_field :without_tax, placeholder:"500", size: "30x1" %>
</div>
<div class="form-group">
  <%= f.label :is_active, "販売ステータス", style:",margin-right:10px;" %>
  <%= f.radio_button :is_active, true %>
  <%= f.label :is_active_true, "販売中", style:"margin-right:20px;" %>
  <%= f.radio_button :is_active, false %>
  <%= f.label :is_active_false, "販売停止中", style:"margin-right:20px;" %>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 my-5 bg-brown">
      <h3>商品編集</h3>
    </div>
    <%= render 'error' %>
  </div>
  <div class="row">
    <div class="col-6 mx-auto">
      <%= form_with model: @item, url: admin_item_path, method: :patch do |f| %>
       <%= render 'form', f: f, genres: @genres %>
       <div class="fo-m-group text-center">
         <%= f.submit "変更を保存", class:"btn btn-success btn-lg" %>
       </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 my-5">
      <h3 class="d-inline-block bg-brown">商品一覧　</h3>
       <% if flash[:notice].present? %>
        <div class="alert alert-success">
         <%= flash[:notice] %>
        </div>
       <% end %>
      <div class="d-inline-block ml-5">
        <%= link_to "＋", new_admin_item_path, class:"btn btn-outline-secondary rounded-circle p-0 d-flex align-items-center justify-content-center", style:"width:2rem;height:2rem;" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <table class="table">
        <thead class="bg-brown">
          <th style="width: 10%">商品ID</th>
          <th style="width: 30%">商品名</th>
          <th style="width: 15%">税抜価格</th>
          <th style="width: 20%">ジャンル</th>
          <th style="width: 15%">ステータス</th>
        </thead>
        <tbody>
          <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td><%= link_to item.name, admin_item_path(item) %></td>
            <td><%= item.without_tax.to_s(:delimited) %></td>
            <td><%= item.genre.name %></td>
            <td>
              <% if item.is_active == true %>
               <p class="text-success">販売中</p>
              <% else %>
               <p class="text-secondary">販売停止中</p>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="d-flex justify-content-center mt-3 custom-pagination">
        <%= paginate @items %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-3 my-5 bg-brown">
      <h3>商品新規登録</h3>
    </div>
    <%= render 'error' %>
  </div>
  <div class="row">
    <div class="mx-auto">
     <%= form_with model: @item, url: admin_items_path do |f| %>
      <%= render 'form', f: f, genres: @genres %>
     <div class="form-group text-center">
      <%= f.submit "新規登録", class:"btn btn-success" %>
     </div>
     <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-2 my-5 bg-brown">
      <h3>商品詳細</h3>
    </div>
  </div>
  <%= render 'flash' %>
  <div class="row">
    <div class="col-4">
      <%= image_tag @item.get_item_image(500, 500), size: "300x200" %>
    </div>
    <div class="col-8">
      <table class="table table-borderless">
        <tr>
          <td>商品名</td>
          <td><%= @item.name %></td>
        </tr>
        <tr>
          <td>商品説明</td>
          <td><%= @item.introduction %></td>
        </tr>
        <tr>
          <td>ジャンル</td>
          <td><%= @item.genre.name %></td>
        </tr>
        <tr>
          <td>税込価格<br>(税抜価格)</td>
          <td><%= @item.add_tax_price.to_s(:delimited) %>（<%= @item.without_tax.to_s(:delimited) %>）円</td>
        </tr>
        <tr>
          <td>販売ステータス</td>
          <% if @item.is_active %>
            <td class="text-success">販売中</td>
          <% else %>
            <td class="tex-secondary">販売停止中</td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
  <div class="text-center">
    <%= link_to "編集する", edit_admin_item_path(@item), class:"btn btn-success btn-lg" %>
  </div>
</div>