config/routes.rb
Rails.application.routes.draw do
 # 管理者用
  devise_for :admin, skip: [:registrations, :password], controllers: {
  sessions: "admin/sessions"
  }
# 顧客用
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

# 管理者側のルーティング
  namespace :admin do
    root to: 'home#top'
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update, :index] do
      collection do
        get 'customer_orders'
      end
    end
    resources :order_details, only: [:update]
    end

# 顧客側のルーティング
  scope module: :public do
    root to: 'homes#top'
    get 'search' => 'searches#search'
    get 'admin/search' => "searches#admin_search"#顧客側検索
    get 'about' => 'homes#about'
    get 'customers/mypage' => 'customers#show'
    get 'customers/infomation/edit' => 'customers#edit'
    patch 'customers/infomation' => 'customers#update'
    get 'customers/confirm' => 'customers#confirm'
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      #collection doは７つのアクション以外の独自のアクションをリソースに追加するものです
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
    resources :addresses, except: [:new, :show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :last_name, presence: true#氏名が空白はだめ
  validates :first_name, presence: true#名前が空白はだめ
  validates :last_name_kana, presence: true#フリガナが空白はだめ
  validates :first_name_kana, presence: true#フリガナが空白はだめ
  validates :postcode, presence: true#郵便番号が空白はだめ
  validates :address, presence: true#住所が空白はだめ
  validates :phone_number, presence: true#電話番号が空白はだめ
  
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postcode, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :email, presence: true, uniqueness: true
  
   def full_name
    "#{last_name} #{first_name}"
   end
   
   def full_name_kana
     "#{last_name_kana} #{first_name_kana}"
   end
  
  def active_for_authentication?
    # is_deletedがfalseならtrueを返すようにしている
    super && (is_deleted == false)
  end
  
  def self.search_by_full_name(query)
    query.delete!(' ')
    Customer.where("first_name || ' ' || last_name LIKE ?", "%#{query}%")
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
   before_action :authenticate_admin!

  def index
    @customer = Customer.all
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "登録情報を変更しました"
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana,
    :first_name_kana, :postcode, :address, :phone_number, :email, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_error.html.erb
<% if @customer.errors.any? %>
  <ul class="alert alert-danger" role="alert">
    <h6 class="alert-heading">
      <%= @customer.errors.count %>件のエラーが発生しました
    </h6>
   <% @customer.errors.full_messages.each do |message| %>
    <li><%= message %></li>
   <% end %>
  </ul>
<% end %>

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-4 my-5 bg-brown">
      <h3><%= @customer.full_name %>さんの会員情報編集</h3>
    </div>
    <%= render 'error' %>
  </div>
  <div class="row">
    <div class="col-9">
       <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>
          <table class="table table-borderless">
            <tr>
              <td>会員ID</td>
              <td>　　　　<%= @customer.id %></td>
              <td></td>
            </tr>
            <tr>
              <td>氏名</td>
              <td>
               （姓） 　<%= f.text_field :last_name %>
               <%= "　 " %>
               （名） 　<%= f.text_field :first_name %>
              </td>
            </tr>
            <tr>
              <td>フリガナ</td>
              <td>
               （セイ） <%= f.text_field :last_name_kana %>
               <%= "　 " %>
               （メイ） <%= f.text_field :first_name_kana %>
              </td>
            </tr>
            <tr>
              <td>郵便番号</td>
              <td>　　　　<%= f.text_field :postcode %></td>
            </tr>
            <tr>
              <td>住所</td>
              <td>　　　　<%= f.text_field :address, :size=>"60" %></td>
            </tr>
            <tr>
              <td>電話番号</td>
              <td>　　　　<%= f.text_field :phone_number %></td>
            </tr>
            <tr>
              <td>メールアドレス</td>
              <td>　　　　<%= f.text_field :email %></td>
            </tr>
            <tr>
              <td>会員ステータス</td>
              <td>
                  　　　　　　<%= f.radio_button :is_deleted, false %><%= f.label :有効 %>
                  　　　　　　<%= f.radio_button :is_deleted, true %><%= f.label :退会 %>
              </td>
            </tr>
            <tr>
              <td></td>
              <td><%= f.submit "変更を保存", class: "btn btn-success btn-lg" %></td>
            </tr>
          </table>
        <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-2 my-5 bg-brown">
      <h3> 会員一覧</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-9">
      <table class="table">
        <thead>
          <tr class="bg-brown">
            <th style="width: 10%">会員ID</th>
            <th style="width: 30%">氏名</th>
            <th style="width: 40%">メールアドレス</th>
            <th style="width: 20%">ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
          <tr>
           <td><%= customer.id %></td>
           <td><%= link_to customer.full_name, admin_customer_path(customer.id), class:"link-order-customer" %></td>
           <td><%= customer.email %></td>
           <td>
             <% if customer.is_deleted == false %>
              <p class="text-success">有効</p>
             <% else %>
              <p class="text-secondary">退会</p>
             <% end %>
           </td>
          </tr>
         <% end %>
        </tbody>
      </table>
      <div class="d-flex justify-content-center mt-3 custom-pagination">
        <%= paginate @customers %>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-2 my-5 bg-brown">
      <h3>会員詳細</h3>
    </div>
  </div>
  <% if flash[:notice].present? %>
   <div class="alert alert-success">
     <%= flash[:notice] %>
   </div>
  <% end %>
  <div class="row">
    <div class="col-10">
      <table class="table table-borderless">
        <tr>
          <td>会員ID</td>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <td>氏名</td>
          <td><%= @customer.full_name %></td>
        </tr>
        <tr>
          <td>フリガナ</td>
          <td><%= @customer.full_name_kana %></td>
        </tr>
        <tr>
          <td>郵便番号</td>
          <td><%= @customer.postcode %></td>
        </tr>
        <tr>
          <td>住所</td>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <td>電話番号</td>
          <td><%= @customer.phone_number %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <td>会員ステータス</td>
          <% if @customer.is_deleted == false %>
            <td class="text-success">有効</td>
          <% else %>
            <td class="tex-secondary">退会</td>
          <% end %>
        </tr>
        <tr>
          <td></td>
          <td><%= link_to "編集する", edit_admin_customer_path(@customer), class:"btn btn-success btn-lg" %></td>
          <td><%= link_to "注文履歴一覧を見る", admin_orders_path, class:"btn btn-primary btn-lg" %></td>
        </tr>
      </table>
    </div>
  </div>
</div>