config/routes.rb
Rails.application.routes.draw do
 # 管理者用
  devise_for :admin, skip: [:registrations, :password], controllers: {
  sessions: "admin/sessions"
  }
# 顧客用
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

# 管理者側のルーティング
  namespace :admin do
    root to: 'home#top'
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update, :index] do
      collection do
        get 'customer_orders'
      end
    end
    resources :order_details, only: [:update]
    end

# 顧客側のルーティング
  scope module: :public do
    root to: 'homes#top'
    get 'search' => 'searches#search'
    get 'admin/search' => "searches#admin_search"#顧客側検索
    get 'about' => 'homes#about'
    get 'customers/mypage' => 'customers#show'
    get 'customers/infomation/edit' => 'customers#edit'
    patch 'customers/infomation' => 'customers#update'
    get 'customers/confirm' => 'customers#confirm'
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      #collection doは７つのアクション以外の独自のアクションをリソースに追加するものです
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
    resources :addresses, except: [:new, :show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait: 0, check: 1, making: 2, prepare: 3, complete: 4 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @orders = Order.all
    @orders = Order.page(params[:page])
  end

  def show
    @order = Order.find(params[:id])
    @total = @order.order_details.inject(0) {|sum, order_detail| sum + order_detail.total_price }
  end

 def update
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
    if @order.update(order_params)
      if @order.status == "check"
       @order_details.update_all(making_status: "wait")
      else
         making_status_complete = @order_details.all? { |order_detail| order_detail.making_status == "complete" }
          if making_status_complete
             @order.update(status: "prepare") 
          else
             @order_details.each do |order_detail|
            if order_detail.making_status == "making"
              @order.update(status: "making")
              break
            end
           end
          end
          if making_status_complete
            @order.update(status: "complete")
          end
      end
    end
    redirect_to admin_order_path(@order)
 end
 
 def customer_orders
     customer_id = params[:customer_id]
     @orders = Order.where(customer_id: customer_id)
     @order = Order.find(params[:customer_id])
 end

  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/customer_orders.html.erb
<div class="container">
  <div class="row">
    <h2 class="d-inline-block bg-brown my-5"><%= @order.customer.full_name %>さんの注文履歴</h2>
    <table class="table mt-3">
      <thead class="bg-brown">
        <tr>
          <th>購入日時</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
      </thead>
      
      <tbody>
        <% @orders.each do |order| %>
        <tr>
          <td>
            <%= link_to admin_order_path(order.id), class:"link-order-time" do %>
              <%= order.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
            <% end %>
          </td>
          <td><%= order.order_details.sum(:amount)%></td>
          <td><%= order.status_i18n %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 my-5">
      <% if flash[:notice].present? %>
        <div class="alert alert-success">
         <%= flash[:notice] %>
        </div>
       <% end %>
      <h3 class="d-inline-block bg-brown mb-5">注文履歴一覧　</h3>
        <table class="table">
          <thead class="bg-brown">
            <tr>
              <th style="width: 25%">購入日時</th>
              <th style="width: 30%">購入者</th>
              <th style="width: 20%">注文個数</th>
              <th style="width: 25%">注文ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @orders.each do |order| %>
              <tr>
                <td><%= link_to admin_order_path(order.id), class:"link-order-time" do %>
                        <%= order.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
                    <% end %>
                </td>
                <td><%= link_to order.customer.full_name, customer_orders_admin_orders_path(customer_id: order.customer.id), method: :get %></td>
                <td><%= order.order_details.sum(:amount) %></td>
                <td><%= order.status_i18n %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="d-flex justify-content-center mt-3 custom-pagination">
            <%= paginate @orders %>
        </div>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-3 my-5 bg-brown">
     <h3>注文履歴詳細</h3>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <table class="table table-borderless">
        <tr>
          <th>購入者</th>
          <td>
            <%= link_to admin_customer_path(@order.customer_id), class:"link-order-customer" do %>
            <%= @order.customer.full_name %> 様
            <% end %>
          </td>
        </tr>
        <tr>
          <th>注文日</th>
          <td>
            <%= @order.created_at.strftime("%Y/%m/%d") %>
          </td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>
            〒<%= @order.postcode %><span> </span><%= @order.addresses %></br>
            <%= @order.name %>
          </td>
        </tr>
        <tr>
          <th>支払い方法</th>
          <td>
            <%= @order.payment_method_i18n %>
          </td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>
            <%= form_with model: @order, url: admin_order_path, method: :patch do |f| %>
              <%= f.select :status, Order.statuses_i18n.invert %>
              <%= f.submit "更新" , class: "btn btn-success ml-4" %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
   </div>
   <div class="row">
    <div class="col-9">
      <table class="table border-bottom">
        <thead>
          <tr class="bg-brown">
            <th><b>商品名</b></th>
            <th><b>単価（税込）</b></th>
            <th><b>数量</b></th>
            <th><b>小計</b></th>
            <th><b>製作ステータス</b></th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= order_detail.include_tax.to_s(:delimited) %></td>
            <td><%= order_detail.amount %></td>
            <td><%= order_detail.total_price.to_s(:delimited) %></td>
            <td>
              <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch do |f| %>
                <%= f.select :making_status, OrderDetail.making_statuses_i18n.invert %>
                <%= f.submit "更新", class:"btn btn-success ml-2" %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-3 d-flex align-items-end">
      <table class="table table-borderless">
        <tr><th class="font-weight-bold">商品合計</th><td><%= (@order.total_price).to_s(:delimited) %>円</td></tr>
        <tr><th class="font-weight-bold">送料</th><td><%= @order.postage %>円</td></tr>
        <tr><th class="font-weight-bold">ご請求額</th><th><%= (@order.total_price + @order.postage).to_s(:delimited) %>円</th></tr>
      </table>
    </div>
   </div>
  </div>
</div>