config/routes.rb
Rails.application.routes.draw do
 # 管理者用
  devise_for :admin, skip: [:registrations, :password], controllers: {
  sessions: "admin/sessions"
  }
# 顧客用
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

# 管理者側のルーティング
  namespace :admin do
    root to: 'home#top'
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update, :index] do
      collection do
        get 'customer_orders'
      end
    end
    resources :order_details, only: [:update]
    end

# 顧客側のルーティング
  scope module: :public do
    root to: 'homes#top'
    get 'search' => 'searches#search'
    get 'admin/search' => "searches#admin_search"#顧客側検索
    get 'about' => 'homes#about'
    get 'customers/mypage' => 'customers#show'
    get 'customers/infomation/edit' => 'customers#edit'
    patch 'customers/infomation' => 'customers#update'
    get 'customers/confirm' => 'customers#confirm'
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      #collection doは７つのアクション以外の独自のアクションをリソースに追加するものです
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
    resources :addresses, except: [:new, :show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :postcode, presence: true
  validates :address, presence: true
  validates :name, presence: true
  
  def address_display
    '〒' + postcode + ' ' + address + ' ' + name + ' 様 '
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  def subtotal #小計
    item.add_tax_price * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :last_name, presence: true#氏名が空白はだめ
  validates :first_name, presence: true#名前が空白はだめ
  validates :last_name_kana, presence: true#フリガナが空白はだめ
  validates :first_name_kana, presence: true#フリガナが空白はだめ
  validates :postcode, presence: true#郵便番号が空白はだめ
  validates :address, presence: true#住所が空白はだめ
  validates :phone_number, presence: true#電話番号が空白はだめ
  
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postcode, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :email, presence: true, uniqueness: true
  
   def full_name
    "#{last_name} #{first_name}"
   end
   
   def full_name_kana
     "#{last_name_kana} #{first_name_kana}"
   end
  
  def active_for_authentication?
    # is_deletedがfalseならtrueを返すようにしている
    super && (is_deleted == false)
  end
  
  def self.search_by_full_name(query)
    query.delete!(' ')
    Customer.where("first_name || ' ' || last_name LIKE ?", "%#{query}%")
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: { message: "ジャンル名を入力してください" }
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :item_image
  has_many :order_details

  validates :name, presence: true
  validates :introduction, presence: true
  validates :without_tax, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :is_active, inclusion: { in: [true, false] }
  
  def get_item_image(width, height)
    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      item_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpg')
    end
    item_image.variant(resize_to_limit: [width, height]).processed
  end
  
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre
  
  def  add_tax_price #単価(税込)
    (self.without_tax * 1.1).round
  end
  
  def self.looks(word)
    @item = Item.where("name LIKE?", "%#{word}%")#入力したwordが商品の名前に引っかかっているか
  end
  
  def self.search_for(word)
    Item.where('name LIKE ?', '%' + word + '%')
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait: 0, check: 1, making: 2, prepare: 3, complete: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  
  enum making_status: {
    impossible: 0,
    wait: 1,
    making: 2,
    complete: 3
  }
  
  def total_price
    include_tax * amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "ジャンル名を登録しました"
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render "index"
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "ジャンル名を変更しました"
      redirect_to admin_genres_path
    else
      render "edit"
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.all
    @item = Item.all
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @genres = Genre.all
    if @item.save
      flash[:notice] = "商品情報を登録しました"
      redirect_to admin_item_path(@item)
    else
      render "new"
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @genres = Genre.all
    if @item.update(item_params)
      flash[:notice] = "商品情報を変更しました"
      redirect_to admin_item_path(@item)
    else
      render "edit"
    end
  end

  private

  def item_params
    params.require(:item).permit(:item_image, :name, :introduction, :genre_id, :without_tax, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
      root_path
    end

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :phone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row">
    <div class="col-3 text-left mt-3">
      <%= image_tag "logo.png", alt: "LOGO", size: "250x75" %>
     <p class="footer-guide"><i class="fa-solid fa-square-phone" style="color: #d1d1d2; font-size: 40px;"></i><span class="underline-text"> 0123-456-789</span></p>
     <h3>(10:00~18:00受付)</h3>
    </div>
    <div class="col-6 mx-auto mt-3">
      <h3>nagano cake(SNS)</h3>
       <table class="table text-light">
         <tr>
           <th><i class="fa-brands fa-instagram" style="color: #cfcfcf; font-size: 40px;"></i></br>instagram</th>
           <th><i class="fa-brands fa-facebook" style="color: #cfcece; font-size: 40px"></i></br>facebook</th>
           <th><i class="fa-brands fa-x-twitter" style="color: #cdced0; font-size: 40px"></i></br>X(旧Twitter)</th>
           <th><i class="fa-brands fa-line" style="color: #cfcfcf; font-size: 40px"></i></br>LINE</th>
         </tr>
       </table>
        © NaganoCake Co.,Ltd. All Rights Reserved.
    </div>
    <div class="col-3 mt-3">
     <table class="table text-light table-borderless text-left">
       <tr><td><i class="fa-solid fa-play" style="color: #ffffff;"></i>ご利用ガイド</td></tr>
       <tr><td><i class="fa-solid fa-play" style="color: #ffffff;"></i>　よくあるご質問</td></tr>
       <tr><td><i class="fa-solid fa-play" style="color: #ffffff;"></i>　プライバシーポリシー</td></tr>
       <tr><td><i class="fa-solid fa-play" style="color: #ffffff;"></i>　特定商取引法表示</td></tr>
       <tr><td><i class="fa-solid fa-play" style="color: #ffffff;"></i>　お問い合わせ</td></tr>
     </table>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
    <header>
      <nav class="navbar navbar-expand-lg py-3 bg-choco">
        <div class = "container">
          <%= link_to root_path, class: "mx-0" do %>
            <% image_tag "logo.png", alt: "LOGO", size: "280x70" %>
          <% end %>
          <% if customer_signed_in? %>
            <p class="mx-2 text-light">ようこそ、<%= current_customer.last_name %> 様</p>
          <% end %>
          <div class="d-flex flex-column">
            <div class="collapse navbar-collapse">
              <ul class="navbar-nav">
                <% if customer_signed_in? %>
                  <li class="nav-item"><%= link_to "マイページ", customers_mypage_path, class: "btn btn-outline-light text-light nav-link ml-2" %></li>
                  <li class="nav-item"><%= link_to "商品一覧", items_path, class: "btn btn-outline-light text-light nav-link ml-2" %></li>
                  <li class="nav-item"><%= link_to "カート", cart_items_path, class: "btn btn-outline-light text-light nav-link ml-2" %></li>
                  <li class="nav-item"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-light text-light nav-link ml-2" %></li>
                <% elsif admin_signed_in? %>
                  <li class="nav-item"><%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-light text-light nav-link ml-2" %></li>
                  <li class="nav-item"><%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-light text-light nav-link ml-2" %></li>
                  <li class="nav-item"><%= link_to "注文履歴一覧", admin_orders_path, class: "btn btn-outline-light text-light nav-link ml-2" %></li>
                  <li class="nav-item"><%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-light text-light nav-link ml-2" %></li>
                  <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-light text-light nav-link ml-2" %></li>
                <% else %>
                  <li class="nav-item"><%= link_to "About", about_path, class: "btn btn-outline-light text-light nav-link ml-2" %></li>
                  <li class="nav-item"> <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-light text-light nav-link ml-2" %></li>
                  <li class="nav-item"> <%= link_to "商品一覧", items_path, class: "btn btn-outline-light text-light nav-link ml-2" %></li>
                  <li class="nav-item">  <%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-light text-light nav-link ml-2" %></li>
                <% end %>
              </ul>
            </div>
            <div class="search_form mt-2 text-right">
              <%= render 'layouts/search' %>
            </div>
         </div>
        </div>
      </nav>
    </header>

app/views/layouts/_search.html.erb
<!--管理者がログインしている場合は商品も顧客も検索できるように分岐-->
<% if current_admin %>
  <%= form_with url: admin_search_path, local: true, method: :get do |f| %>
    <%= f.select :range, options_for_select([['顧客'], ['商品']]) %>
    <%= f.text_field :word, placeholder: "Search" %>
    <%= f.submit "検索", class: "btn-sm btn-light" %>
  <% end %>
<% else %>
  <%= form_with url: search_path, local: true, method: :get do |f| %>
    <%= f.text_field :word, placeholder: "Search" %>
    <%= f.submit "検索", class: "btn-sm btn-light" %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/60b6d7d28b.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+Decol&display=swap" rel="stylesheet">
  </head>
  <body>
      <%= render 'layouts/header' %>
    <main class="main-bg">
      <%= yield %>
    </main>
    <footer class="footer-bg text-light text-center">
     <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>